from datetime import date
from pathlib import Path

from fpdf import FPDF
from sqlalchemy.orm import Session

from backend.app.core.config import settings
from backend.app.models import Report


def build_report_filename(campus: str, report_date: date) -> str:
    campus_slug = campus.strip().replace(" ", "_").lower()
    return f"sustainability_report_{campus_slug}_{report_date.isoformat()}.pdf"


def generate_report_pdf(campus: str, report_date: date, generated_by: int | None = None) -> bytes:
    pdf = FPDF(format="A4")
    pdf.add_page()
    pdf.set_font("Helvetica", size=16)
    pdf.cell(0, 10, "Campus Sustainability Report", ln=True, align="C")
    pdf.set_font("Helvetica", size=12)
    pdf.ln(8)
    pdf.cell(0, 8, f"Campus: {campus}", ln=True)
    pdf.cell(0, 8, f"Date: {report_date.isoformat()}", ln=True)
    pdf.ln(8)
    pdf.multi_cell(
        0,
        7,
        (
            "This report captures a short-term sustainability forecast for campus resources, "
            "including energy, water, waste, and emissions. Generated by the backend reporting "
            "service, it can be downloaded or stored alongside report metadata."
        ),
    )
    pdf.ln(6)
    pdf.cell(0, 8, "Key recommendations:", ln=True)
    pdf.set_font("Helvetica", size=11)
    pdf.multi_cell(0, 6, "1. Optimize HVAC asset schedules based on occupied hours.")
    pdf.multi_cell(0, 6, "2. Review chilled water system setpoints for evening operation.")
    pdf.multi_cell(0, 6, "3. Track water fixture performance per building.")
    return pdf.output(dest="S").encode("latin-1")


def create_report_record(
    db: Session,
    campus: str,
    file_name: str,
    pdf_bytes: bytes | None = None,
    generated_by: int | None = None,
) -> Report:
    output_dir = Path(settings.report_output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    file_path = output_dir / file_name
    if pdf_bytes is not None:
        file_path.write_bytes(pdf_bytes)
    report = Report(
        generated_by=generated_by,
        file_path=str(file_path),
        campus=campus,
    )
    db.add(report)
    db.commit()
    db.refresh(report)
    return report

